# Site settings
title: El blog de Diego
email: dauscateguir@unal.edu.co
description: > # this means to ignore newlines until "baseurl:"
  Este es el blog académico de Diego Alejandro Uscategui Russi 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uskategi.github.io/" # the base hostname & protocol for your site

github_username:  uskategi

# Build settings
markdown: kramdown
